/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author angelynz95
 */
public class HideMessagePanel extends javax.swing.JPanel {

    /**
     * Creates new form HideMessagePanel
     */
    public HideMessagePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browseImageTextField = new javax.swing.JTextField();
        browseMessageTextField = new javax.swing.JTextField();
        browseImageButton = new javax.swing.JButton();
        browseMessageButton = new javax.swing.JButton();
        coverImagePanel = new javax.swing.JPanel();
        keyLabel = new javax.swing.JLabel();
        keyTextField = new javax.swing.JTextField();
        thresholdLabel = new javax.swing.JLabel();
        thresholdTextField = new javax.swing.JTextField();
        encryptionLabel = new javax.swing.JLabel();
        encryptionYesRadioButton = new javax.swing.JRadioButton();
        encryptionNoRadioButton = new javax.swing.JRadioButton();
        convertButton = new javax.swing.JButton();

        browseImageTextField.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        browseMessageTextField.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        browseImageButton.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        browseImageButton.setText("Browse Image");

        browseMessageButton.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        browseMessageButton.setText("Browse Message");

        coverImagePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout coverImagePanelLayout = new javax.swing.GroupLayout(coverImagePanel);
        coverImagePanel.setLayout(coverImagePanelLayout);
        coverImagePanelLayout.setHorizontalGroup(
            coverImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        coverImagePanelLayout.setVerticalGroup(
            coverImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        keyLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        keyLabel.setText("Key");

        keyTextField.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        thresholdLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        thresholdLabel.setText("Threshold");

        thresholdTextField.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        encryptionLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        encryptionLabel.setText("Encryption");

        encryptionYesRadioButton.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        encryptionYesRadioButton.setText("Yes");

        encryptionNoRadioButton.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        encryptionNoRadioButton.setText("No");

        convertButton.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        convertButton.setText("Convert");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(browseImageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                            .addComponent(browseMessageTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(browseImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(browseMessageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(convertButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(coverImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keyTextField)
                            .addComponent(thresholdTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(encryptionLabel)
                                    .addComponent(thresholdLabel)
                                    .addComponent(keyLabel)
                                    .addComponent(encryptionYesRadioButton)
                                    .addComponent(encryptionNoRadioButton))
                                .addGap(0, 274, Short.MAX_VALUE)))))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseImageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseImageButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseMessageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseMessageButton))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coverImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(keyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(thresholdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(encryptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(encryptionYesRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(encryptionNoRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(convertButton)))
                .addGap(76, 76, 76))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_convertButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseImageButton;
    private javax.swing.JTextField browseImageTextField;
    private javax.swing.JButton browseMessageButton;
    private javax.swing.JTextField browseMessageTextField;
    private javax.swing.JButton convertButton;
    private javax.swing.JPanel coverImagePanel;
    private javax.swing.JLabel encryptionLabel;
    private javax.swing.JRadioButton encryptionNoRadioButton;
    private javax.swing.JRadioButton encryptionYesRadioButton;
    private javax.swing.JLabel keyLabel;
    private javax.swing.JTextField keyTextField;
    private javax.swing.JLabel thresholdLabel;
    private javax.swing.JTextField thresholdTextField;
    // End of variables declaration//GEN-END:variables
}
