/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.FlowLayout;

/**
 *
 * @author angelynz95
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        hideMessagePanel.setLayout(new FlowLayout());
        hideMessagePanel.add(new HideMessagePanel());
        extractMessagePanel.setLayout(new FlowLayout());
        extractMessagePanel.add(new ExtractMessagePanel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        hideMessagePanel = new javax.swing.JPanel();
        extractMessagePanel = new javax.swing.JPanel();

        mainTabbedPane.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        javax.swing.GroupLayout hideMessagePanelLayout = new javax.swing.GroupLayout(hideMessagePanel);
        hideMessagePanel.setLayout(hideMessagePanelLayout);
        hideMessagePanelLayout.setHorizontalGroup(
            hideMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1195, Short.MAX_VALUE)
        );
        hideMessagePanelLayout.setVerticalGroup(
            hideMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("Hide Message", hideMessagePanel);

        javax.swing.GroupLayout extractMessagePanelLayout = new javax.swing.GroupLayout(extractMessagePanel);
        extractMessagePanel.setLayout(extractMessagePanelLayout);
        extractMessagePanelLayout.setHorizontalGroup(
            extractMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1195, Short.MAX_VALUE)
        );
        extractMessagePanelLayout.setVerticalGroup(
            extractMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("Extract Message", extractMessagePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel extractMessagePanel;
    private javax.swing.JPanel hideMessagePanel;
    private javax.swing.JTabbedPane mainTabbedPane;
    // End of variables declaration//GEN-END:variables
}
