/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import processor.Steganography;

/**
 *
 * @author William Sentosa - 13513026
 * @author Candy Olivia Mawalim - 13513031
 * @author Angela Lynn - 13513032
 */
public class StegoImageFrame extends javax.swing.JFrame {
    private Steganography stego;
    private image.Image coverImage;
    private String stegoImageName;
    private String coverImagePath;

    /**
     * Creates new form StegoImageFrame
     */
    public StegoImageFrame() throws IOException {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2 - 20);
        stego = HideMessagePanel.getStego();
        coverImage = HideMessagePanel.getCoverImage();
        stegoImageName = HideMessagePanel.getStegoImageName();
        coverImagePath = HideMessagePanel.getCoverImagePath();
        
        showImage();
        showQuality();
    }
    
    private void showImage() throws IOException {
        File coverFile = new File (stego.getImage().getPath());
        Image image = ImageIO.read(new File(coverFile.getParent() + "\\" + stegoImageName + ".png"));
        if ((stego.getImage().getPixel().length > stegoImageLabel.getWidth()) && (stego.getImage().getPixel()[0].length > stegoImageLabel.getHeight())) {
            if (stego.getImage().getPixel().length > stego.getImage().getPixel()[0].length) {
                stegoImageLabel.setIcon(new ImageIcon(image.getScaledInstance(stegoImageLabel.getWidth(), -1, Image.SCALE_SMOOTH)));
            } else {
                stegoImageLabel.setIcon(new ImageIcon(image.getScaledInstance(-1, stegoImageLabel.getHeight(), Image.SCALE_SMOOTH)));
            }
        } else if (stego.getImage().getPixel().length > stegoImageLabel.getWidth()) {
            stegoImageLabel.setIcon(new ImageIcon(image.getScaledInstance(stegoImageLabel.getWidth(), -1, Image.SCALE_SMOOTH)));
        } else if (stego.getImage().getPixel()[0].length > stegoImageLabel.getHeight()) {
            stegoImageLabel.setIcon(new ImageIcon(image.getScaledInstance(-1, stegoImageLabel.getHeight(), Image.SCALE_SMOOTH)));
        } else {
            stegoImageLabel.setIcon(new ImageIcon(image));
        }
    }
    
    private void showQuality() {
        File coverFile = new File(stego.getImage().getPath());
        image.Image cover = new image.Image(coverImagePath);
        image.Image stegoImage = new image.Image(coverFile.getParent() + "\\" + stegoImageName + ".png");
        cover.convertImageToBlocks();
        stegoImage.convertImageToBlocks();
        qualityValueLabel.setText(String.valueOf(stego.getImage().checkImageQuality(cover.getPixel(), stegoImage.getPixel())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qualityLabel = new javax.swing.JLabel();
        qualityValueLabel = new javax.swing.JLabel();
        stegoImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        qualityLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        qualityLabel.setText("Quality");

        qualityValueLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        qualityValueLabel.setToolTipText("");

        stegoImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stegoImageLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(stegoImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(qualityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qualityValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stegoImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(qualityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qualityValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(230, 230, 230)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StegoImageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StegoImageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StegoImageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StegoImageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new StegoImageFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(StegoImageFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel qualityLabel;
    private javax.swing.JLabel qualityValueLabel;
    private javax.swing.JLabel stegoImageLabel;
    // End of variables declaration//GEN-END:variables
}
